---
- lineinfile: dest=~/.bash_profile line='# for exenv by ansible-mac-setup'
- lineinfile: dest=~/.bash_profile line='export PATH="$HOME/.exenv/bin:$PATH"'
- lineinfile: dest=~/.bash_profile line='eval "$(exenv init -)"'

- name: source ~/.bash_profile
  shell: source ~/.bash_profile

- name: install latest elixir
  shell: exenv install $(exenv install -l | grep -v - | grep -v Docs | grep -v master | grep -v dev | grep -v versions | sort | tail -1)

- name: set latest elixir version
  shell: |
    exenv global $(exenv install -l | grep -v - | grep -v Docs | grep -v master | grep -v dev | grep -v versions | sort | tail -1)
    exenv rehash

