---

# TODO: versionを変数化する

- name: check elixir installed or not
  shell: "[ -e ~/.exenv/versions/1.2.3 ] && echo 'Installed' || echo ''"
  register: elixir_installed

- name: install elixir with exenv
  shell: exenv install 1.2.3
  when: (not elixir_installed.stdout)

- lineinfile: dest=~/.bash_profile line='# for exenv by ansible-mac-setup'
- lineinfile: dest=~/.bash_profile line='export PATH="$HOME/.exenv/bin:$PATH"'
- lineinfile: dest=~/.bash_profile line='eval "$(exenv init -)"'

- name: set elixir version
  shell: |
    exenv global 1.2.3
    exenv rehash

