---
- lineinfile: dest=~/.bash_profile line='# for exenv by ansible-mac-setup'
- lineinfile: dest=~/.bash_profile line='export PATH="$HOME/.exenv/bin:$PATH"'
- lineinfile: dest=~/.bash_profile line='eval "$(exenv init -)"'

- name: source ~/.bash_profile
  shell: source ~/.bash_profile

- name: install latest elixir
  shell: exenv install $(elixir-build --definitions | grep -v zip | grep -v dev | grep -v master | sort | tail -1)

- name: set latest elixir version
  shell: |
    exenv global $(elixir-build --definitions | grep -v zip | grep -v dev | grep -v master | sort | tail -1)
    exenv rehash

