---

- name: install latest golang
  shell: asdf install golang $(asdf list-all golang | grep -v beta | grep -v rc | tail -n 1)

- name: set latest golang version
  shell: asdf global golang $(asdf list-all golang | grep -v beta | grep -v rc | tail -n 1)
