---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    #- java    # add java env
    #- android # add android-studio env
    - brew
    #- brew-cask
    #- ruby
    #- erlang # FIXME: env disabled at first time
    #- elixir # FIXME: env disabled at first time
    #- node   # FIXME: run once
    #- python
    #- font
    #- zsh
  vars:
    brew_repos:
      # for font
      - sanemat/font
      # for rsync
      - homebrew/dupes
      # for avr
      - osx-cross/homebrew-avr
      # for homebrew-services
      - homebrew/services
      # for php
      - homebrew/php
    brew_packs:
      # for language
      - { name: rbenv }
      - { name: ruby-build }
      - { name: pyenv }
      - { name: pyenv-virtualenv }
      - { name: pyenv-virtualenvwrapper }
      - { name: kerl }
      - { name: rebar }
      - { name: exenv }
      - { name: elixir-build }
      - { name: nodebrew }
      - { name: v8 }
      - { name: golang }
      - { name: gauche }
      - { name: composer }
      # for database
      - { name: redis }
      - { name: mysql }
      # for aws
      - { name: awscli }
      # for heroku
      - { name: heroku }
      # for docker
      - { name: unison }
      - { name: fswatch }
      - { name: rsync }
      - { name: fsevent_watch }
      - { name: fsevents-tools }
      # for terraform
      - { name: terraform }
      - { name: tfenv }
      # for bigdata
      - { name: apache-spark }
      - { name: kafka }
      # for server manage
      - { name: consul }
      # for font
      - { name: fontforge }
      - { name: ricty }
      # for libs
      - { name: openssl }
      - { name: libffi }
      # for books
      - { name: ghostscript }
      # for life
      - { name: neovim }
      - { name: jq }
      - { name: graphviz }
      - { name: htop }
      - { name: coreutils }
      - { name: zsh }
      - { name: git }
      - { name: ghq }
      - { name: wget }
      - { name: sqlite }
      - { name: peco }
      - { name: tree }
      # for testing
      - { name: tsung }
      - { name: selenium-server-standalone }
      - { name: geckodriver }
      # for ergodox
      - { name: avr-binutils }
      - { name: avr-gcc }
      - { name: avr-gcc49 }
      - { name: avr-libc }
      - { name: avr-libc49 }
      - { name: dfu-programmer }
      - { name: teensy_loader_cli }
    brew_cask_repos:
    brew_cask_packs:
      # for language
      - { name: java }
      # for android
      - { name: android-studio }
      # for docker
      - { name: docker }
      # for vagrant
      - { name: vagrant }
      - { name: virtualbox }
      # for font
      - { name: xquartz }
      # for book
      - { name: mactex }
      # for life
      - { name: appcleaner }
      - { name: daisydisk }
      - { name: iterm2 }
      - { name: evernote }
      - { name: dropbox }
      - { name: firefox }
      - { name: google-chrome }
      - { name: slack }
      - { name: kindle }
      - { name: android-file-transfer }
      # for IDE
      - { name: jetbrains-toolbox }
      # for writing
      - { name: mactex }
      - { name: atom }
      - { name: karabiner-elements }

# for font
  handlers:
    - name: run fc-cache
      shell: fc-cache -vf

