
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - java
    - brew
    - brew-cask
    - asdf
    - font
    - zsh
  vars:
    brew_repos:
      # for font
      - sanemat/font
      # for rsync
      #- homebrew/dupes
      # for avr
      - osx-cross/homebrew-avr
      # for homebrew-services
      - homebrew/services
      # for php
      #- homebrew/php
    brew_packs:
      # for languages
      - { name: asdf }
      - { name: v8 }
      - { name: gauche }
      - { name: composer }
      # for database
      - { name: redis }
      - { name: mysql@5.6 }
      # for aws
      - { name: awscli }
      - { name: s3cmd }
      # for heroku
      - { name: heroku }
      # for docker
      - { name: unison }
      - { name: fswatch }
      - { name: rsync }
      - { name: fsevent_watch }
      - { name: fsevents-tools }
      # for bigdata
      - { name: apache-spark }
      - { name: kafka }
      - { name: embulk }
      # for font
      - { name: fontforge }
      - { name: ricty }
      # for libs
      - { name: openssl }
      - { name: libffi }
      # for books
      - { name: ghostscript }
      # for life
      - { name: neovim }
      - { name: jq }
      - { name: graphviz }
      - { name: htop }
      - { name: coreutils }
      - { name: gpg }
      - { name: zsh }
      - { name: git }
      - { name: ghq }
      - { name: wget }
      - { name: sqlite }
      - { name: peco }
      - { name: tree }
      # for testing
      - { name: selenium-server-standalone }
      - { name: geckodriver }
      # for ergodox
      - { name: avr-binutils }
      - { name: avr-gcc }
      - { name: avr-gcc49 }
      - { name: avr-libc }
      - { name: avr-libc49 }
      - { name: dfu-programmer }
      - { name: teensy_loader_cli }
      # for IoT
      - { name: fwup }
      - { name: squashfs }
    brew_cask_repos:
      # for java
      - homebrew/cask-versions
      # for health
      - homebrew/cask-drivers
    brew_cask_packs:
      # for language
      - { name: java8 }
      # for dotnet
      - { name: dotnet }
      # for docker
      - { name: docker }
      # for vagrant
      - { name: vagrant }
      - { name: virtualbox }
      # for font
      - { name: xquartz }
      # for book
      - { name: mactex }
      # for life
      - { name: appcleaner }
      - { name: daisydisk }
      - { name: iterm2 }
      - { name: evernote }
      - { name: dropbox }
      - { name: firefox }
      - { name: google-chrome }
      - { name: slack }
      - { name: kindle }
      - { name: android-file-transfer }
      - { name: elmedia-player }
      - { name: steam }
      # for IDE
      - { name: jetbrains-toolbox }
      # for writing
      - { name: mactex }
      - { name: atom }
      - { name: visual-studio-code }
      - { name: karabiner-elements }

# for font
  handlers:
    - name: run fc-cache
      shell: fc-cache -vf

