---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - brew
    - brew-cask
    - java
    - ruby
    - erlang
    - elixir
    - node
    - font
    - zsh
  vars:
    brew_repos:
      # for font
      - sanemat/font
    brew_packs:
      # for language
      - { name: rbenv }
      - { name: ruby-build }
      - { name: kerl }
      - { name: rebar }
      - { name: exenv }
      - { name: elixir-build }
      - { name: nodebrew }
      # for font
      - { name: fontforge }
      - { name: ricty }
      # for libs
      - { name: openssl }
      - { name: libffi }
      # for books
      - { name: ghostscript }
      # for life
      - { name: coreutils }
      - { name: zsh }
      - { name: git }
      - { name: wget }
      - { name: sqlite }
    brew_cask_repos:
    brew_cask_packs:
      # for language
      - { name: java }
      # for font
      - { name: xquartz }
      # for VM
      - { name: virtualbox }
      - { name: vagrant }
      # for book
      - { name: mactex }
      # for life
      - { name: iterm2 }
      - { name: evernote }
      - { name: dash }
      - { name: firefox }
      - { name: google-chrome }
      - { name: slack }
      - { name: kindle }

# for font
  handlers:
    - name: run fc-cache
      shell: fc-cache -vf

