---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - java    # add java env
    - android # add android-studio env
    - brew
    - brew-cask
    - ruby
    - erlang # FIXME: env disabled at first time
    - elixir # FIXME: env disabled at first time
    - node   # FIXME: run once
    - font
    - zsh
  vars:
    brew_repos:
      # for font
      - sanemat/font
    brew_packs:
      # for language
      - { name: rbenv }
      - { name: ruby-build }
      - { name: kerl }
      - { name: rebar }
      - { name: exenv }
      - { name: elixir-build }
      - { name: nodebrew }
      # for database
      - { name: redis }
      - { name: mysql }
      # for bigdata
      - { name: apache-spark }
      # for font
      - { name: fontforge }
      - { name: ricty }
      # for libs
      - { name: openssl }
      - { name: libffi }
      # for books
      - { name: ghostscript }
      # for life
      - { name: coreutils }
      - { name: zsh }
      - { name: git }
      - { name: wget }
      - { name: sqlite }
    brew_cask_repos:
    brew_cask_packs:
      # for language
      - { name: java }
      # for docker
      - { name: docker }
      # for font
      - { name: xquartz }
      # for book
      - { name: mactex }
      # for life
      - { name: appcleaner }
      - { name: iterm2 }
      - { name: evernote }
      - { name: firefox }
      - { name: google-chrome }
      - { name: slack }
      - { name: kindle }
      - { name: android-file-transfer }

# for font
  handlers:
    - name: run fc-cache
      shell: fc-cache -vf

