- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - brew-cask
    - brew
    - alias
    - dotenv
    - asdf
    - k8s
    - font
    - zsh
  vars:
    brew_repos:
      # for font
      - sanemat/font
      # for rsync
      #- homebrew/dupes
      # for avr
      #- osx-cross/homebrew-avr
      # for homebrew-services
      #- homebrew/services
      # for php
      #- homebrew/php
      # for heroku
      - heroku/brew
      # for wxmac
      #- homebrew/core
    brew_packs:
      # for languages
      - { name: asdf, state: latest }
      - { name: roswell, state: latest }
      - { name: gpg, state: latest }
      #- { name: v8 }
      #- { name: gauche }
      #- { name: composer }
      # for erlang compile
      # - { name: wxmac, state: absent }
      - { name: wxwidgets } # rename from wxmac
      - { name: fop }
      - { name: unixodbc, state: latest }
      # for java compile
      #- { name: ant }
      # for k8s
      - { name: kubernetes-cli }
      - { name: kube-ps1 }
      - { name: kubectx, state: absent }
      - { name: stern, state: absent }
      - { name: cfssl } # for k8s-the-hard-way
      # for aws
      - { name: awscli, state: absent }
      - { name: s3cmd, state: absent }
      - { name: aws-iam-authenticator, state: absent }
      #- { name: kayac/tap/ecspresso }
      # for heroku
      #- { name: heroku }
      # for docker
      #- { name: docker, state: absent }
      #- { name: docker-completion, state: absent }
      #- { name: docker-compose, state: absent }
      #- { name: unison }
      #- { name: fswatch }
      #- { name: rsync }
      #- { name: fsevent_watch }
      #- { name: fsevents-tools }
      # for bigdata
      #- { name: apache-spark }
      #- { name: kafka }
      #- { name: embulk }
      # for font
      - { name: fontforge, state: absent } # move to cask
      - { name: ricty }
      # for libs
      #- { name: openssl }
      #- { name: libffi }
      # for books
      #- { name: ghostscript }
      # for life
      - { name: tmux }
      - { name: neovim }
      - { name: jq }
      - { name: htop, state: absent }
      - { name: bpytop, state: latest }
      #- { name: coreutils }
      #- { name: gnupg }
      - { name: zsh }
      - { name: git }
      - { name: ghq }
      - { name: wget }
      - { name: peco }
      - { name: tree }
      - { name: fzf }
      #- { name: openldap }
      #- { name: pwgen }
      #- { name: p7zip }
      - { name: hugo, state: latest }
      #- { name: graphviz }
      # for testing
      #- { name: selenium-server-standalone }
      #- { name: geckodriver }
      # for ergodox
      #- { name: avr-binutils }
      #- { name: avr-gcc }
      #- { name: avr-gcc49 }
      #- { name: avr-libc }
      #- { name: avr-libc49 }
      #- { name: dfu-programmer }
      #- { name: teensy_loader_cli }
      # for IoT
      #- { name: fwup }
      #- { name: squashfs }
      #- { name: coreutils }
      #- { name: xz }
      # for Python/Poetry
      - { name: pkg-config }
      - { name: tcl-tk }
    brew_cask_repos:
      # for java
      #- homebrew/cask-versions
      # for health
      #- homebrew/cask-drivers
      #- homebrew/core
    brew_cask_packs:
      # for language
      #- { name: java }
      #- { name: javacc }
      # for vagrant
      #- { name: vagrant }
      #- { name: virtualbox }
      # for font
      #- { name: xquartz }
      # for book
      #- { name: mactex }
      # for life
      #- { name: appcleaner }
      #- { name: daisydisk }
      - { name: iterm2, state: absent }
      - { name: wezterm, state: latest }
      - { name: evernote, state: latest }
      - { name: notion, state: latest }
      - { name: dropbox, state: latest }
      #- { name: firefox }
      #- { name: google-chrome, state: absent }
      - { name: slack, state: latest }
      - { name: kindle, state: absent }
      #- { name: android-file-transfer }
      #- { name: elmedia-player }
      #- { name: steam }
      - { name: forticlient-vpn, state: absent }
      - { name: docker, state: latest }
      # for IDE
      - { name: jetbrains-toolbox, state: latest }
      - { name: visual-studio-code, state: latest }
      - { name: visual-studio, state: latest }
      - { name: cursor, state: latest }
      - { name: windsurf, state: latest }
      #- { name: arduino }
      #- { name: thonny }
      # for AI
      - { name: claude, state: latest }
      # for writing
      #- { name: mactex }
      - { name: karabiner-elements, state: latest }
      - { name: dynalist }
      # for Gaming
      - { name: unity-hub, state: latest }
      - { name: godot, state: latest }
      #- { name: parsec }
      #- { name: zerotier-one }
      # for Design
      - { name: adobe-creative-cloud, state: latest }
      - { name: figma }
      # for meeting
      - { name: zoom, state: latest }
      #- { name: bluejeans }
      - { name: discord, state: latest }
      # for bicycle
      #- { name: garmin-express }
      #- { name: zwift, state: absent }
      # for stream
      - { name: loupedeck }
      #- { name: obs }
      - { name: microsoft-remote-desktop }
      # for font
      - { name: fontforge }

# for font
  handlers:
    - name: run fc-cache
      shell: fc-cache -vf

