---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - brew
    - brew-cask
    - ruby
    - elixir
  vars:
    brew_repos:
    brew_packs:
      # language
      - { name: rbenv }
      - { name: ruby-build }
      - { name: exenv }
      - { name: elixir-build }
    brew_cask_repos:
    brew_cask_packs:

