---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - brew
    - brew-cask
    - java
    - ruby
    - erlang
    - elixir
    - font
  vars:
    brew_repos:
      # for font
      - sanemat/font
    brew_packs:
      # for language
      - { name: rbenv }
      - { name: ruby-build }
      - { name: kerl }
      - { name: rebar }
      - { name: exenv }
      - { name: elixir-build }
      # for font
      - { name: fontforge }
      - { name: ricty }
      # for libs
      - { name: openssl }
    brew_cask_repos:
    brew_cask_packs:
      # for language
      - { name: java }
      # for font
      - { name: xquartz }
      # for life
      - { name: iterm2 }
      - { name: evernote }
      - { name: dash }
      - { name: firefox }
      - { name: google-chrome }

# for font
  handlers:
    - name: run fc-cache
      shell: fc-cache -vf

