---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - brew
    - brew-cask
    - ruby
    - elixir
    - font
  vars:
    brew_repos:
      # for font
      - sanemat/font
    brew_packs:
      # for language
      - { name: rbenv }
      - { name: ruby-build }
      - { name: exenv }
      - { name: elixir-build }
      # for font
      - { name: fontforge }
      - { name: ricty }
    brew_cask_repos:
    brew_cask_packs:
      # for font
      - { name: xquartz }

# for font
  handlers:
    - name: run fc-cache
      shell: fc-cache -vf

