---
- lineinfile: dest=~/.bash_profile line='# for kerl by ansible-mac-setup'
- lineinfile: dest=~/.bash_profile line='KERL_CONFIGURE_OPTIONS="--enable-kernel-poll --enable-threads --enable-dynamic-ssl-lib --enable-smp-support --enable-darwin-64bit --disable-hipe --disable-native-libs --disable-sctp --without-javac --without-odbc --without-wx --with-ssl=/usr/local/opt/openssl"'

- name: source ~/.bash_profile
  shell: source ~/.bash_profile

- name: create installation dir
  file: path=~/.kerl/erlang state=directory mode=0755

- name: update releases
  shell: kerl update releases

# TODO: run once
- name: build latest erlang
  shell: kerl build $(kerl list releases | head -1 | awk '{print $NF}') $(kerl list releases | head -1 | awk '{print $NF}')

# TODO: run once
- name: install latest erlang
  shell: kerl install $(kerl list releases | head -1 | awk '{print $NF}') ~/.kerl/erlang/$(kerl list releases | head -1 | awk '{print $NF}')

- lineinfile: dest=~/.bash_profile line='source ~/.kerl/erlang/$(kerl list releases | head -1 | awk "{print \$NF}")/activate'

- name: source ~/.bash_profile
  shell: source ~/.bash_profile
