---
- lineinfile: dest=~/.zshrc line='# for loading alias by ansible-mac-setup'
- lineinfile: dest=~/.zshrc line='source ~/Dropbox/common-conf/alias.sh'

- name: copy alias file
  copy:
    src: ../files/alias.sh
    dest: ~/Dropbox/common-conf/alias.sh
    mode: 0755
