---
#- lineinfile: dest=~/.bash_profile line='export HOMEBREW_GITHUB_API_TOKEN="{YOUR_API_TOKEN}"'
- lineinfile: dest=~/.zshrc line='# for brew by ansible-mac-setup'
#- lineinfile: dest=~/.zshrc line='eval $(/opt/homebrew/bin/brew shellenv)'
#- lineinfile: dest=~/.zshrc line='eval $(/usr/local/bin/brew shellenv)'

#- name: check opt sym link
#  stat: path=/usr/local/opt
#  register: optsymlink

#- name: create sym link
#  become: true
#  file:
#    src: /opt/homebrew/opt
#    dest: /usr/local/opt
#    state: link
#  when: not optsymlink.stat.exists

- name: tap brew repositories
  homebrew_tap: tap={{ item }} state=present
  with_items: '{{ brew_repos }}'
  when: brew_repos | default([]) | length > 0

- name: update brew
  homebrew: update_homebrew=yes

- name: install/upgrade brew packages
  homebrew: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
    install_options={{
      item.install_options | default([])
    }}
  with_items: '{{ brew_packs }}'
  when: brew_packs | default([]) | length > 0

