---
#- lineinfile: dest=~/.bash_profile line='# for brew-cask by ansible-mac-setup'
#- lineinfile: dest=~/.bash_profile line='export HOMEBREW_CASK_OPTS="--caskroom=/Applications"'
#
#- name: source ~/.bash_profile
#  shell: source ~/.bash_profile

#- name: install/upgrade brew cask
#  homebrew: name=brew-cask state=latest

- name: tap external brew cask repositories
  homebrew_tap: tap={{ item }} state=present
  with_items: '{{ brew_cask_repos }}'
  when: brew_cask_repos

- name: install/upgrade brew cask packages
  homebrew_cask: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('present') }}
  with_items: '{{ brew_cask_packs }}'
  when: brew_cask_packs

