---
- lineinfile: dest=~/.bash_profile line='# for rbenv by ansible-mac-setup'
- lineinfile: dest=~/.bash_profile line='export PATH="$HOME/.rbenv/bin:$PATH"'
- lineinfile: dest=~/.bash_profile line='eval "$(rbenv init -)"'

- name: install latest ruby
  shell: rbenv install -s $(rbenv install -l | grep -v - | tail -1)

- name: set latest ruby version
  shell: |
    rbenv global $(rbenv install -l | grep -v - | tail -1)
    rbenv rehash

- name: installs latest bundler
  gem: name=bundler user_install=False state=latest

